micronaut:
  application:
    name: helloWorld
  server:
    port: 8080

datasources:
  default:
    url: jdbc:mysql://localhost:3306/micronautdb
    username: root
    password: root

jpa:
  default:
    # Entities are scanned in the package example.micronaut.domain.
    packages-to-scan:
      - 'hello.world'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

logging:
  level:
    root: info